POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username" : "nguyensivan",
    "password" : "123456"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username" : "nguyensivan",
    "name": "Nguyễn Sĩ Văn",
    "email": "nguyensivan1998@gmail.com",
    "dateOfBirth": "11/04/1998",
    "sex": "nu",
    "password" : "123456",
    "confirmPassword": "123456"
}

###
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsIl9pZCI6IjVkYjkzNTg2YTRlOGFhM2M4MGVhNjVhYyIsInVzZXJuYW1lIjoibmd1eWVuc2l2YW4iLCJuYW1lIjoibmd1eeG7hW4gc8SpIHbEg24iLCJlbWFpbCI6Im5ndXllbnNpdmFuMTk5OEBnbWFpbC5jb20iLCJkYXRlT2ZCaXJ0aCI6IjExLzA0LzE5OTgiLCJzZXgiOiJu4buvIiwiY3JlYXRlZEF0IjoiMjAxOS0xMC0zMFQwNzowMjozMC44MjdaIiwidXBkYXRlZEF0IjoiMjAxOS0xMC0zMVQxNjo1NDozMC45MjFaIiwiX192IjowLCJ1c2VySW1hZ2UiOiIvdXBsb2Fkcy9hdmF0YXJfNWRiOTM1ODZhNGU4YWEzYzgwZWE2NWFjIiwiaWF0IjoxNTcyNTgxMDE5LCJleHAiOjE1NzMxODU4MTl9.vOmfLnVVMwDsFByAoGfCinfKEXAB3NfZ61J-tv5BBYE

###
POST http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsIl9pZCI6IjVkYjkzNTg2YTRlOGFhM2M4MGVhNjVhYyIsInVzZXJuYW1lIjoibmd1eWVuc2l2YW4iLCJuYW1lIjoibmd1eeG7hW4gc8SpIHbEg24iLCJlbWFpbCI6Im5ndXllbnNpdmFuMTk5OEBnbWFpbC5jb20iLCJkYXRlT2ZCaXJ0aCI6IjExLzA0LzE5OTgiLCJzZXgiOiJu4buvIiwiY3JlYXRlZEF0IjoiMjAxOS0xMC0zMFQwNzowMjozMC44MjdaIiwidXBkYXRlZEF0IjoiMjAxOS0xMC0zMVQxNjo1NDozMC45MjFaIiwiX192IjowLCJ1c2VySW1hZ2UiOiIvdXBsb2Fkcy9hdmF0YXJfNWRiOTM1ODZhNGU4YWEzYzgwZWE2NWFjIiwiaWF0IjoxNTcyNTgxMDE5LCJleHAiOjE1NzMxODU4MTl9.vOmfLnVVMwDsFByAoGfCinfKEXAB3NfZ61J-tv5BBYE

{
    "_id" : "5db93586a4e8aa3c80ea65ac",
    "username" : "nguyensivan",
    "name": "Nguyễn Sĩ Văn",
    "email": "nguyensivan1998@gmail.com",
    "dateOfBirth": "11/04/1997",
    "sex": "nu",
    "newPassword" : "123456",
    "confirmNewPassword": "123456"
}